### ISSUE TITLE
Is the CC3200SDK-SERVICEPACK package included?

### ISSUE THREAD

**Issue by jamesturner246** [DKrepsky/CC3200-Linux-SDK#1]
Hi DKrepsky.

Does this package include the CC3200SDK-SERVICEPACK 1.0.0.10.0 package?

Thanks,
James.

**Comment by DKrepsky** [comment]
Nope, only the SDK 1.1.0.

But it's a good ideia to include it, since one can upgrade the sp through the OTA example.

I'll add it asap into the "others" folder.

**Comment by jamesturner246** [comment]
Excellent. Thanks!
